### ISSUE TITLE
Suggest adding -ObjC to OTHER_LINKER_FLAGS in Getting Started guide

### ISSUE THREAD

**Issue by genegoykhman** [Giphy/giphy-ios-sdk#138]
Hey friends :wave:

We just ran into a snag with instantiating `GiphyViewController` causing a crash in a Swift app that didn't have `-ObjC` listed in `OTHER_LINKER_FLAGS`. I noticed that the SDK sample app has that flag so I added it to ours as well and it fixed things right up. Maybe that's something to add to the Getting Started Guide?

Here's the exact message when we tried to `present` GiphyViewController:

```
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GiphyUISDK.GiphySearchController registerKeyboardNotifications]: unrecognized selector sent to instance 0x127241e00'
```

**Comment by cgmaier** [comment]
hey @genegoykhman ! wow what a trip seeing you here :) thanks for reaching out about this 

the `-ObjC` flag is indeed strange - in the past it has only been necessary for for Carthage // not CocoaPods, but it appears it's become necessary to support Mac Catalyst. we have a task to learn more about the flag and see if there's a way we can adjust the SDK build settings so it's not necessary to the 

in the meantime, I'll go ahead and add this to the docs!

**Comment by cgmaier** [comment]
hey @genegoykhman ! with the latest release, we've switched over to dynamic framework, which makes it so that the flag is not necessary. we can do this new that we have finally built our own native solutions for all our dependencies.

https://github.com/Giphy/giphy-ios-sdk/releases

**Comment by genegoykhman** [comment]
Yup @cgmaier updating to 2.1.3 did the trick. No more `-ObjC` required. Thanks!
