### ISSUE TITLE
Uncaught exception in -[GiphyUISDK.GiphySearchController registerKeyboardNotifications]:

### ISSUE THREAD

**Issue by Aurazion** [Giphy/giphy-ios-sdk#139]
Hello,
I'm facing with a very weird crash, since I updated to Firebase SDK (7.5.0) (!), everytime when I present the `GiphyViewController`, I got this exception :
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GiphyUISDK.GiphySearchController registerKeyboardNotifications]: unrecognized selector sent to instance 0x7ffab0923c00'
```
Very strange but everything works well with Firebase SDK v7.4.0 and I can't debug the `registerKeyboardNotifications` method because the source code is not available.

Here is my code for opening the Giphy VC :

```
    public func openGiphy() {
        let giphyVC = GiphyViewController()
        giphyVC.mediaTypeConfig = [.recents, .gifs]
        giphyVC.theme = GPHTheme(type: .light)
        giphyVC.shouldLocalizeSearch = true
        giphyVC.delegate = self
        self.present(giphyVC, animated: true, completion: nil)
    }
```

Could you take a look please ? I'm on the latest version (2.1.2) of the Giphy SDK

**Comment by cgmaier** [comment]
hey @Aurazion very sorry about this! please add `ObjC` to `Other Linker Flags` under Build Settings. We hope to have a solution so adding the flag isn't necessary in a future release.

**Comment by Aurazion** [comment]
Thanks for your answer, I already have the `-ObjC` flag in my build settings but it still crash since Firebase was updated to the latest version. 🤷‍♂️
