### ISSUE TITLE
Not compiling on 2.1.4 installed from Pods

### ISSUE THREAD

**Issue by m1entus** [Giphy/giphy-ios-sdk#142]
Hey, seems you have issue with newest version, i just wanted to bump from 2.0.9 to 2.1.4 and i am getting No such module 'GiphyUISDK', when i install 2.1.3 all is working fine, i am testing on iPhone 12 mini simulator.

**Comment by cgmaier** [comment]
hey @m1entus thanks - 2.1.4 is working now. sorry about that!

**Comment by m1entus** [comment]
@cgmaier Hey hmm, i have still issue, i am fetching from 'https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/2.1.4/Giphy.podspec' because 2.1.4 is not found on Pods trunk.

**Comment by cgmaier** [comment]
can you try clearing your cache? 
```
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update
```

**Comment by m1entus** [comment]
Ok all good, thanks
