### ISSUE TITLE
Giphy SDK gets unintentionally copied into AppClip

### ISSUE THREAD

**Issue by arthurschiller** [Giphy/giphy-ios-sdk#151]
Hi,

I've just migrated migrated over to the Swift Package Manager version of the SDK and while uploading my app to AppStore Connect I've got the following error: ITMS-90680 (Screenshot attached).
Apparently this is caused by the framework being copied over into the AppClips folder of the app (which is not intended).
I've got the same issue with Instabug's SPM version but Firebase for example (which of course also isn't included within the AppClip) behaves as intended.
Do you have any ideas how I can solve this? The SDK is only marked to be embedded within the main app.

I've had a look into the archived app and the framework is indeed showing up there.
I guess for now I could try removing it manually before upload but it would be great to find a solution nevertheless.

This issue is probably related: [https://forums.swift.org/t/swift-package-binary-framework-issue/41922/7](https://forums.swift.org/t/swift-package-binary-framework-issue/41922/7)

Thanks and best regards

![appstore-connect_error](https://user-images.githubusercontent.com/3637723/114011150-326c2880-9865-11eb-9790-3f9bb7bc5872.jpg)
![appclips-folder](https://user-images.githubusercontent.com/3637723/114010685-aeb23c00-9864-11eb-9e15-18433c11d912.png)

**Comment by cgmaier** [comment]
hey @arthurschiller I'm hoping this will have been resolved with Xcode 12.5

please see my comment on a related issue here: https://github.com/Giphy/giphy-ios-sdk/issues/149#issuecomment-834870156
