### ISSUE TITLE
Weird Keyboard behaviour when opening GiphyViewController

### ISSUE THREAD

**Issue by Rytikov** [Giphy/giphy-ios-sdk#153]
![Simulator Screen Shot - iPhone 12 - 2021-04-21 at 10 51 35](https://user-images.githubusercontent.com/10780470/115517451-d0adb480-a28f-11eb-96c8-4de8e3abec5a.png)

Steps to reproduce issue:

1) Show GiphyViewController
2) Tap on Text field and Start type a few symbols in Text field
3) Scroll up until the keyboard is disappeared
4) Tap on Text field

Actual result: Weird  Interface behaviour

Expected result: Keyboard on screen or correct interface behaviour.

Please fix this issue.

**Comment by cgmaier** [comment]
hey @Rytikov I'm unable to reproduce this issue, though I have experienced similar issues in the simulator if the 'software keyboard' is not enabled. command-k can be used to toggle the software keyboard. hope this helps!
