### ISSUE TITLE
How to use GPHCache with Objective C?

### ISSUE THREAD

**Issue by cihadturhan** [Giphy/giphy-ios-sdk#154]
I can't find `GPHCache` definition although I imported all the headers
```objc

#import <GiphyUISDK/GiphyUISDK-Swift.h>
#import <GiphyUISDK/GiphyUISDK.h>
#import <GiphyUISDK/GiphyYYAnimatedImageView.h>
#import <GiphyUISDK/GiphyYYImageCoder.h>
#import <GiphyUISDK/GiphyYYFrameImage.h>
#import <GiphyUISDK/GiphyYYImage.h>
```

and used clear method
```objc
[[GPHCache shared] clear];
```
But can't find GPHcache class
`Use of undeclared identifier 'GPHCache'`

**Comment by cgmaier** [comment]
hey @cihadturhan sorry about that. while `GPHCache` was marked `@objcMembers`, it was necessary for it to also extend `NSObject`. this is fixed in the latest release [2.1.8](https://github.com/Giphy/giphy-ios-sdk/releases/tag/v2.1.8)
