### ISSUE TITLE
GiphyYYAnimatedImageView.animationDuration returns 0

### ISSUE THREAD

**Issue by jscalo** [Giphy/giphy-ios-sdk#156]
`animationDuration` is a property of `UIImageView` which `GiphyYYAnimatedImageView` inherits from. I think `GiphyYYAnimatedImageView` should override `animationDuration` and return the correct value.

(The same could probably be said for `UIImageView.animationImages` but for now I really just need to know the animation duration 😀)

iOS SDK v2.1.8

**Comment by cgmaier** [comment]
hey @jscalo we also addressed this issue in this release. again, appears I forgot to note it in this issue! 
https://github.com/Giphy/giphy-ios-sdk/releases/tag/v2.1.10
