### ISSUE TITLE
GiphyGridController.cellPadding has no effect

### ISSUE THREAD

**Issue by jscalo** [Giphy/giphy-ios-sdk#158]
`GiphyGridController.cellPadding` seems to have no effect.

```
        gridController = GiphyGridController()
        gridController.delegate = self
        gridController.direction = .vertical
        gridController.view.backgroundColor = UIColor.white
        gridController.theme = GPHTheme(type: .light)
        gridController.cellPadding = 4 // not doing anything?
        gridController.numberOfTracks = 2
        gridController.addAsChild(parentVC: self, containerView: containerView)
        gridController.content = GPHContent.trending(mediaType: .gif)
        gridController.update()
```

Result:

![image](https://user-images.githubusercontent.com/2917357/118514915-7ff87280-b6fa-11eb-91b3-c3080f81d674.png)

iOS SDK 2.8.1

**Comment by cgmaier** [comment]
hey @jscalo this was addressed a while back in this release - https://github.com/Giphy/giphy-ios-sdk/releases/tag/v2.1.10

could have sworn I noted it in this issue but appears not! sorry about that.
