### ISSUE TITLE
How to save giphy into local data base? 

### ISSUE THREAD

**Issue by PNSona** [Giphy/giphy-ios-sdk#161]
I have saved the media.url into local data base but not able to show it on other page later on
 
// delegate method where i get the media.url or media
 func didSelectMedia(media: GPHMedia, cell: UICollectionViewCell) {
            
        self.dismiss(animated: true, completion: {
            self.delegate?.getSelectedGiphy(mediaUrl: media.url , media: media)
       })
    }
// to load giphy i have used media 
var  giphyImageView = GPHMediaView()
   func loadGif(mediaURL: String,media:GPHMedia) {
        if mediaURL != "" {
            giphyImageView.media = media
            giphyView.addSubview(giphyImageView)
         }
    }

how to load using media.url ?
and if i store this media.url into local data base how to show it again?
do i need to store media also? if yes then how?

**Comment by cgmaier** [comment]
hey @PNSona can you try a media id based solution? as documented here: 
https://github.com/Giphy/giphy-ios-sdk/blob/main/Docs.md#media-ids

**Comment by PNSona** [comment]
Hi Christopher Maier,

 Thank you for your response.
 This solution is working for me.
