### ISSUE TITLE
Pod Installation Issue

### ISSUE THREAD

**Issue by jordangustafson** [Giphy/giphy-ios-sdk#165]
There are appears to be an issue when installing the latest version of the Giphy SDK (2.1.9). It looks like the path to the framework isn't being properly added to the `.xcodeproj`. This results in the `No such module 'GiphyUISDK'` error when adding `import GiphyUISDK` to a file. This issue only seems to occur with `2.1.9`, using `2.1.8` resolves this issue. We have had version `2.1.9` added to our project since June when it released, but just a few days ago this issue started occurring in our CI pipeline.

### Environment
- Xcode 12.5
- Cocoapods 1.10.1

## Reproduction Steps
1. Create a new Xcode project with the App template
2. Navigate to the project folder and run `pod init` to get a pod file created
3. Add `pod 'Giphy', '2.1.9'` to the pods in the pod file
4. Run a `pod install` in the root of the project to install the pod
5. Add `import GiphyUISDK` to the top of the `AppDelegate.swift` file
6. Build the project and observe the `No such module 'GiphyUISDK'` error
7. Modify the Giphy version in the pod file to `pod 'Giphy', '2.1.8'`
8. Run a `pod install` in the root of the project to install the pod
9. Build the project and observe that the issue is resolved.

**Comment by m1entus** [comment]
I have same issue on newes Xcode 13 Beta, are you able to resolve that it will compile on newest Xcode ?

**Comment by jordangustafson** [comment]
@m1entus  I have tried it on Xcode 12.4, 12.5, and 13, I can reproduce the issue on all of them
