### ISSUE TITLE
Can't load clips to play

### ISSUE THREAD

**Issue by QiJing13** [Giphy/giphy-ios-sdk#166]
Follow instruct create and add the GPHVideoView to my App view:
        let videoView = GPHVideoView()
        videoView.media = media
        view.addSubview(videoView)
        videoView.play()
But the gif is not loaded and no audio is played, just a colored background, have any idea how to resolve this ? Thank you very much!

**Comment by cgmaier** [comment]
Hi @QiJing13 thanks for playing around with GIPHY Clips! Can you please confirm that `media.type == .video`?

**Comment by QiJing13** [comment]
Hi @cgmaier  thanks for reply, I have a if to check media type is GPHMediaTypeVideo

**Comment by QiJing13** [comment]
After set the videoView frame and play the video after about 2 seconds , it show up ,but there is another issue , I will close this one and open another, thank you !
