### ISSUE TITLE
Create Clip type with parameters not working 

### ISSUE THREAD

**Issue by QiJing13** [Giphy/giphy-ios-sdk#169]
Here is the code :
// the parameters are got from one clip giphy return , I want to rebuild the clip with parameters so do not need to save the   
    // whole media 
let media = GPHMedia("7NRNTnJHxITfJjku4Z", type: .video, url: "https://giphy.com/clips/studiosoriginals-reaction-emotion-penguin-7NRNTnJHxITfJjku4Z")
        let videoView = GPHVideoView()
        videoView.media = media
        videoView.frame = CGRect(x: 100, y: 100, width: 200, height: 100)
        self.view.addSubview(videoView)
        videoView.loadVideo()
        DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
            videoView.play()
            videoView.unmute()
        }
But there is no clip play and no voice , just a color background

**Comment by cgmaier** [comment]
hey @QiJing13 apologies for never addressing this. the `GPHMedia` constructor isn't intended for this use case - we're in the process of removing it as a publicly available interface. please use the `getGifById` or `getGifByIds` endpoints to fetch `GPHMedia`
