### ISSUE TITLE
Network response times

### ISSUE THREAD

**Issue by mmdock** [Giphy/giphy-ios-sdk#170]
Not sure where to report this, but in the past few days I have been seeing a large increase in response times for various urls. from giphy that are in use.

Any ideas about this? 

<img width="723" alt="Screen Shot 2021-08-10 at 9 39 21 AM" src="https://user-images.githubusercontent.com/2423465/128899147-9231ac2b-5a61-420f-9018-9ba60ef4f0f3.png">
<img width="701" alt="Screen Shot 2021-08-10 at 9 39 09 AM" src="https://user-images.githubusercontent.com/2423465/128899149-3ba7fd10-e857-4555-b917-6c8e7f7453e5.png">

**Comment by mmdock** [comment]
<img width="692" alt="Screen Shot 2022-01-20 at 11 35 36 AM" src="https://user-images.githubusercontent.com/2423465/150409702-3a8c119d-88fb-42df-bb44-a8e2620a2c39.png">

random webp file takes 40+ seconds starting recently

**Comment by cgmaier** [comment]
hey @mmdock want to thank you for continuing to reporting these sorts of issues. going to close this as it must have been an intermittent backend issue.
