### ISSUE TITLE
[Objective C] No doc for configureWithApiKey 

### ISSUE THREAD

**Issue by cihadturhan** [Giphy/giphy-ios-sdk#176]
Hi,
For project restrictions, I have to use Objective C and looks like you've changed and added new parameter for configure function. Function definitions is like following:

```ObjC
+ (void)configureWithApiKey:(NSString * _Nonnull)apiKey 
             verificationMode:(BOOL)verificationMode 
                         metadata:(NSDictionary<NSString *, NSString *> * _Nonnull)metadata;
```

What are these `verificationMode` and `metadata`?

**Comment by ALexanderLonsky** [comment]
hey @cihadturhan,

There is a verification flow available under the web dashboard, however, it’s not required for production approval. You can set it to `false`.

`metadata` is for the SDK's internal needs, please provide an empty dictionary.
