### ISSUE TITLE
Can't build Giphy included project for iOS, only for iOS simulator

### ISSUE THREAD

**Issue by Fibonacci336** [Giphy/giphy-ios-sdk#186]
I recently installed Giphy via Cocoapods and I have not been able to run the project now on any device other than a simulator. 

The primary issue appears to be this:
"ld: building for iOS, but linking in dylib file (*/Build/Products/Debug-iphoneos/GiphyUISDK.framework/GiphyUISDK) built for iOS Simulator, file '*/Build/Products/Debug-iphoneos/GiphyUISDK.framework/GiphyUISDK' for architecture arm64" (* is just the removed path to derived data)

I don't think this can be recompiled and it appears to be because Giphy is downloaded as a framework versus a full-on Cocoapod. This is rather frustrating. Please fix ASAP. I can't appear to find anything online that helps since it is usually the other way around, where people can't run on the simulator but can run on a device. 

Here is another error message:
"error: unable to load standard library for target 'arm64-apple-ios10.0-simulator'"

My theory is that somehow the Giphy framework was compiled for the iOS 10 simulator and now it just won't work. I have made sure that my target version is set throughout to iOS 14 with no luck. 

Since I need this solved ASAP and I am assuming @cgmaier is an admin, I am tagging him here

**Comment by cgmaier** [comment]
hey @Fibonacci336 - sorry about that! we should be able to get this sorted 

what version of Xcode are you on? we compiled the last few versions with Xcode 13 - in the past the Swift compilers across Xcode versions sometimes don't play nice with each other...but I'd have hoped all of those issues would've been resolved by now, especially since we've switched to .xcframeworks 
 
if you're on Xcode 12, and aren't able to update to 13, you can try an older GIPHY SDK version

**Comment by Fibonacci336** [comment]
I am currently on Version 13.1 (13A1030d)

**Comment by cgmaier** [comment]
thanks for clarifying - I'll look into this & try to get back to you by EOD tomorrow

**Comment by Fibonacci336** [comment]
Thank you!

**Comment by cgmaier** [comment]
hey @Fibonacci336 we weren't able to repro on our end. I wonder if it could be a CocoaPods issue - similar to https://github.com/mapbox/mapbox-navigation-ios/issues/2674#issuecomment-703074011

what version of CocoaPods are you on ?

**Comment by Fibonacci336** [comment]
Version 1.9.3

**Comment by Fibonacci336** [comment]
@cgmaier I updated CocoaPods and reinstalled my pods and no change

**Comment by Fibonacci336** [comment]
For anyone in the future: `pod deintegrate`, then delete derived data, then `pod install`
