### ISSUE TITLE
"No gif" is displayed after using for some time

### ISSUE THREAD

**Issue by bhaskarsharecare** [Giphy/giphy-ios-sdk#187]
Task <69948332-70AE-48E2-B4D0-B3F2B67D96BB>.<15917> finished with error [-1000] Error Domain=NSURLErrorDomain Code=-1000 "bad URL" UserInfo={_kCFStreamErrorCodeKey=-2203, NSUnderlyingError=0x6000000664f0 {Error Domain=kCFErrorDomainCFNetwork Code=-1000 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x600002d3dc70 [0x112e21bf0]>{length = 16, capacity = 16, bytes = 0x100201bb97650e020000000000000000}, _kCFStreamErrorCodeKey=-2203, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <69948332-70AE-48E2-B4D0-B3F2B67D96BB>.<15917>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <69948332-70AE-48E2-B4D0-B3F2B67D96BB>.<15917>"
), NSLocalizedDescription=bad URL, NSErrorFailingURLStringKey=https://pingback.giphy.com/v2/pingback?api_key=g, NSErrorFailingURLKey=https://pingback.giphy.com/v2/pingback?api_key=g, _kCFStreamErrorDomainKey=4}

**Comment by ALexanderLonsky** [comment]
hey @bhaskarsharecare,
Please email us at developers@giphy.com with your API key and link to this issue to check your traffic and when you first noticed the issue.
