### ISSUE TITLE
Tap isn't recognized on Suggestion Cell(GPHTermSuggestionCell)

### ISSUE THREAD

**Issue by BalajiAnandan15** [Giphy/giphy-ios-sdk#189]
Tap is only recognized on the icon("trending up-arrow icon" & "@"text) of the UICollectionView Suggestion, I need to recognize the tap action whole to the collection view cell. any update for this solution? Anyone?

Thanks in advance for the help.

**Comment by ALexanderLonsky** [comment]
Hey @BalajiAnandan15,
what SDK version do you use?
We should have fixed that in [v2.1.16](https://github.com/Giphy/giphy-ios-sdk/releases/tag/v2.1.16)

**Comment by BalajiAnandan15** [comment]
> Hey @BalajiAnandan15, what SDK version do you use? We should have fixed that in [v2.1.16](https://github.com/Giphy/giphy-ios-sdk/releases/tag/v2.1.16)

Thanks for the reply, I didn't mention any specific version for the pod in my project, just a stable pod which I'm using now in my iOS - project.

**Comment by ALexanderLonsky** [comment]
hey @BalajiAnandan15.
You can check the current version in your `Podfile.lock` file.

Please be sure to do 
`pod repo update`
right before `pod install` to pull the latest [PodSpecs](https://github.com/CocoaPods/Specs)

As an option, you can specify pod version:
`pod 'Giphy', :podspec => 'https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/2.1.16/Giphy.podspec'`

**Comment by BalajiAnandan15** [comment]
> hey @BalajiAnandan15. You can check the current version in your `Podfile.lock` file.
> 
> Please be sure to do `pod repo update` right before `pod install` to pull the latest [PodSpecs](https://github.com/CocoaPods/Specs)
> 
> As an option, you can specify pod version: `pod 'Giphy', :podspec => 'https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/2.1.16/Giphy.podspec'`

Checked the version on Podfile.lock file it's lower than your mentioned one.
Then tried **pod repo update** and did a **pod install** the pod version didn't update.
Finally specified the Pod version of this **pod 'Giphy', :podspec => 'https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/2.1.16/Giphy.podspec' it got updated and my the issue is sorted now**.

Thanks a lot for your help.

**Comment by ALexanderLonsky** [comment]
> Then tried pod repo update and did a pod install the pod version didn't update.
This is weird because on my end it works, I also had outdated PodSpecs and after the sync, the version became 2.1.16.
