### ISSUE TITLE
GIPHY Clip URL with Audio not working

### ISSUE THREAD

**Issue by lschaupp** [Giphy/giphy-ios-sdk#201]
Hey there,

I am currently exploring this package.
I have noticed that when retrieving the clip media MP4 URL for a specific item (i.e. when a user clicks a GIF),
the link itself leads to a video without any audio. Is there any rendition type that would include the audio channel as well?

Thank you.

**Comment by cgmaier** [comment]
hey @lschaupp ! this is a great question and I apologize for the late reply. 

a `GPHMedia` object represents a specific asset on GIPHY and all its associated metadata. these assets must be 1 of several `GPHMediaType`s, which include `.video`, `.text`, `.gif`, or `.sticker`. the only media type with sound is `.video`

we provide MP4 renditions of gifs / stickers (no sound) to support developers who may prefer to work with video formats in their specific contexts, despite the embedded sound tracks being empty 

for working with GIPHY Clips (GIFs with Sound!), please check out the docs here: 
https://github.com/Giphy/giphy-ios-sdk/blob/main/clips.md

there are specific instructions for accessing the ideal urls for GIPHY Clips
