### ISSUE TITLE
Class PodsDummy_libwebp is implemented in both

### ISSUE THREAD

**Issue by vandyshev** [Giphy/giphy-ios-sdk#202]
## 🐛 Bug Report

 Class PodsDummy_libwebp is implemented in both warning in debug output

## To Reproduce
1. Just run Camera-Example
2. Look at the debug output

## Expected behavior
No warnings in the output

## Actual Behavior
```
objc[94452]: Class PodsDummy_libwebp is implemented in both
/private/var/containers/Bundle/Application/AAB26D77-3E32-407D-AC10-E6EC3BC0414C/camera-example.app/Frameworks/libwebp.framework/libwebp (0x105010238)
and
/private/var/containers/Bundle/Application/AAB26D77-3E32-407D-AC10-E6EC3BC0414C/camera-example.app/Frameworks/GiphyUISDK.framework/GiphyUISDK (0x105b6ced0).
One of the two will be used. Which one is undefined.
```
<img width="1720" alt="image" src="https://user-images.githubusercontent.com/4127205/161794109-2b3324f2-4530-481e-b671-19eadbc29a76.png">

## Your Environment
- Giphy iOS SDK version: 2.1.21
- Dependency Manager: CocoaPods: 1.11.3
- Xcode Version: 13.3
- Swift Version: 5.6
- Device info: Both, Simulator and real device with iOS 15.4 and iOS 14.7.1

## Reproducible Demo
Camera-Example

**Comment by cgmaier** [comment]
hey @vandyshev thanks for flagging this. we'll take a look at updating the camera example and address any issues!
