### ISSUE TITLE
How to set timeout

### ISSUE THREAD

**Issue by carlotaprat** [Giphy/giphy-ios-sdk#203]
I'm trying to decrease the timeout in my requests (specifically for the `getById` method). Is there a way to do it? It seems I can't set it to my GiphyClient.
Thanks!

**Comment by cgmaier** [comment]
hey @carlotaprat, we agree we should provide developers the ability to override the timeout interval. will keep you posted

**Comment by cgmaier** [comment]
hi @carlotaprat we were able to support this request in the latest release! let us know if you have any feedback
https://github.com/Giphy/giphy-ios-sdk/releases/tag/v2.1.22
