### ISSUE TITLE
Can't search for emojis in GiphyGridController

### ISSUE THREAD

**Issue by roimulia2** [Giphy/giphy-ios-sdk#207]
Hey there!

I'm working on the implementation of GiphyGridController. I noticed that there is no option to search/filter emojis (which breaks the UX as the rest has this option.

Any specific reason why can't I search for it?

**Comment by cgmaier** [comment]
hey @roimulia2 thanks for opening this issue! we should add additional documentation to reflect that the `.emoji` content type is not searchable and include some guidance for how to handle that inability in integrations using the `GiphyGridController`.

in the meantime, feel free to check out the `GiphyViewController` experience to see how we opted to address the "discovery"-only aspect of emoji. The gist of it is that tapping into the search bar automatically triggers the selection of a searchable content type, like stickers.

**Comment by roimulia2** [comment]
Thank you @cgmaier! Got it.
