### ISSUE TITLE
Compile error when building for macCatalyst

### ISSUE THREAD

**Issue by m1entus** [Giphy/giphy-ios-sdk#209]
## 🐛 Bug Report

Hey,

When building for macCatalyst i am getting an issue about `bundle format is ambiguous (could be app or framework)` when using Giphy using Pods: `pod 'Giphy', :podspec => 'https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/2.1.22/Giphy.podspec'`. When building on iOS - all is okay. 

Important note - when manually linking xcframework it compiles without a problem.

```
Stripped /Users/m1entus/Library/Developer/Xcode/DerivedData/Geneva-hcoxiqtjwrurhsciwhoxfoisqqxt/Build/Products/dev-debug-maccatalyst/geneva-dev.app/Contents/Frameworks/GiphyUISDK.framework/GiphyUISDK of architectures: x86_64
Code Signing /Users/m1entus/Library/Developer/Xcode/DerivedData/Geneva-hcoxiqtjwrurhsciwhoxfoisqqxt/Build/Products/dev-debug-maccatalyst/geneva-dev.app/Contents/Frameworks/GiphyUISDK.framework with Identity Apple Development: iOS Developer (X3W43S34QS)
/usr/bin/codesign --force --sign 885925582F41AA5E618380E75FFDD70BF9C5E80E  --preserve-metadata=identifier,entitlements '/Users/m1entus/Library/Developer/Xcode/DerivedData/Geneva-hcoxiqtjwrurhsciwhoxfoisqqxt/Build/Products/dev-debug-maccatalyst/geneva-dev.app/Contents/Frameworks/GiphyUISDK.framework'
/Users/m1entus/Library/Developer/Xcode/DerivedData/Geneva-hcoxiqtjwrurhsciwhoxfoisqqxt/Build/Products/dev-debug-maccatalyst/geneva-dev.app/Contents/Frameworks/GiphyUISDK.framework: replacing existing signature
/Users/m1entus/Library/Developer/Xcode/DerivedData/Geneva-hcoxiqtjwrurhsciwhoxfoisqqxt/Build/Products/dev-debug-maccatalyst/geneva-dev.app/Contents/Frameworks/GiphyUISDK.framework: bundle format is ambiguous (could be app or framework)
Command PhaseScriptExecution failed with a nonzero exit code
```

## Expected behavior

Build project without error.

## Actual Behavior

Cannot build App for macCatalyst.

## Your Environment

- Giphy iOS SDK version: 2.1.22
- Dependency Manager: Pods + cocoapods-catalyst-support
- Xcode Version: 14.1
- Swift Version: 5.7
- Device info (Simulator/Device? iOS version? Debug/Release?): macCatalyst m1 simulator

**Comment by m1entus** [comment]
I see that macCatalyst directory of xcframework have additionally `Versions` directory - after deleting it it compiles successfully.

**Comment by m1entus** [comment]
I think the problem is that you are not creating simlinks in `Versions` directory, it should look like this:

```
---------------------------------------------------
xxx.framework
    xxx  ->  Versions/Current/xxx
    Resources  ->  Versions/Current/Resources
    Headers  ->  Versions/Current/Headers
    Versions
----------------------------------------------------
xxx.framework/Versions
    A
    Current  ->  A      
```

**Comment by cgmaier** [comment]
hey @m1entus thanks so much for your investigation! we'll take a look and get back to you soon.

**Comment by m1entus** [comment]
@cgmaier any updates?

**Comment by cgmaier** [comment]
hey @m1entus I haven't been able to reproduce the issue - can successfully compile on my m1 Mac for Mac catalyst using Cocoapods. 
what's `cocoapods-catalyst-support`? I thought that cocoapods added better support for catalyst (xcframeworks in general) a while back

**Comment by Vaberer** [comment]
@cgmaier @m1entus this issue is reproducible for me as well when building mac catalyst :(
```
.../Contents/Frameworks/GiphyUISDK.framework: bundle format is ambiguous (could be app or framework)
```
