### ISSUE TITLE
Crash 'Index out of range'

### ISSUE THREAD

**Issue by alexander-lsvk** [Giphy/giphy-ios-sdk#210]
## 🐛 Bug Report

Crash when search for gifs

## To Reproduce

(Write your steps here:)

1. Search for `halloween`
2. Crash in line **254** `UIImage + SwiftyGif` -> `displayRefreshFactor = displayRefreshFactors[I]`
 **Index out of range**

iOS **15.6.1**
Giphy iOS SDK - **2.1.22** but looks like exists for long time

**Comment by cgmaier** [comment]
hey @alexander-lsvk thanks for opening this issue. are you certain this isn't an issue with [`SwiftyGif`](https://github.com/kirualex/SwiftyGif)? 

we provide a 'GPHMediaView` (or alternatively `GiphyYYAnimatedImageView`) through the GIPHY SDK which you can use for GIF/webp playback.
