### ISSUE TITLE
Promoted Gifs

### ISSUE THREAD

**Issue by mmdock** [Giphy/giphy-ios-sdk#212]
## Use case description
Ability to have branded gifs be the first row of gifs before and after a search

## Proposed solution
when presenting GiphyViewController, can customize a promotion row of gifs that appear, either by passing giphy IDs or by an account identifier etc

this allows for gifs related to our company to appear first, OR we can use it for like, branded direct sold campaigns with advertising partners.  I know Tinder has this capability and does it with their gifs, but I am not sure they use giphy SDK to power theirs.  Would love to do the same

## Alternatives considered
N/A: didn't really think on this that much

**Comment by cgmaier** [comment]
hey @mmdock this isn't possible in the `GiphyViewController` currently but I'll pass your request to my team for future consideration

if you're using the `GiphyGridController` you could pre-populate the grid with an "@user-name" search.
