### ISSUE TITLE
No such module 'GiphyUISDK'

### ISSUE THREAD

**Issue by Patresko** [Giphy/giphy-ios-sdk#214]
## 🐛 Bug Report

I have installed GiphySDK though the Swift package management. 

Name                   Version Rules                Location
GiphyUiSDK         2.2.1 - Next Major        https://github.com/Giphy/giphy-ios-sdk

Once I tried to import to the .swift file Im getting an error from compiler

`No such module 'GiphyUISDK'`

- Giphy iOS SDK version: 2.2.1
- Dependency Manager: Swift package 
- Xcode Version: 14.1 (14B47b)

**Comment by cgmaier** [comment]
hey @Patresko, do you experience the issue if you create a new, empty Xcode project, import the package, and add `import GiphyUISDK` to the `ViewController` class?

**Comment by Patresko** [comment]
I did add by suggestion, but compiler still showing error but I was able to build successfully even with error

**Comment by cgmaier** [comment]
hey @Patresko that's odd! I'll go ahead and close this issue if that's alright. thanks for using the GIPHY SDK!

**Comment by okaris** [comment]
I experience the same issue
