### ISSUE TITLE
White box at bottom (unable to ignore bottom safe area) SwiftUI

### ISSUE THREAD

**Issue by yoyolty** [Giphy/giphy-ios-sdk#215]
Is there any way to ignore the bottom safe area? I am using swiftUI, but the .ignoresSafeArea() have no effects towards this white bottom box, I want the view extended to the bottom of phone. Don't know if the white box is the tab bar or safe area. I used .fullScreenCover to present this view. Thank you!
![IMG_0037](https://user-images.githubusercontent.com/113869377/206379147-2735590d-e0cd-4b7f-9d50-698085a4fcb3.jpg)

**Comment by ALexanderLonsky** [comment]
hey @yoyolty ,
how do you present the dialog?
```
.sheet(isPresented: $showingDialog, content: {
    GiphyPicker()
    .ignoresSafeArea()
})
```
`.ignoresSafeArea()` removes the white box at the bottom on my end:

<img width="300" alt="Screenshot 2022-12-08 at 18 11 25" src="https://user-images.githubusercontent.com/4112/206500342-9d40ebb3-a787-4b0f-8081-7d85d4803035.png">

**Comment by yoyolty** [comment]
hi @ALexanderLonsky Thank you for your reply!
I followed your code but still the white box exist, did you done any special handling in GiphyPicker?
If not, I think there might be some other components in my app that blocks.

**Comment by ALexanderLonsky** [comment]
hi @ylai-msrl,
Sorry about the late reply.
Here is a full snippet:

```
import SwiftUI
import GiphyUISDK

struct GiphyPicker: UIViewControllerRepresentable {
    func makeUIViewController(context: UIViewControllerRepresentableContext<GiphyPicker>) -> GiphyViewController {
        
        Giphy.configure(apiKey: "KEY")
     
        let giphy =
        GiphyViewController()
        GiphyViewController.trayHeightMultiplier = 1.0
        giphy.swiftUIEnabled = true
        giphy.shouldLocalizeSearch = true
        giphy.dimBackground = true
        giphy.mediaTypeConfig = [.gifs]
        giphy.theme = .init(type: .light)
        giphy.modalPresentationStyle = .currentContext
        
        return giphy
    }
}

struct ContentView: View {
    @State private var showingDialog = false
    
    var body: some View {
        Button("Show Giphy Dialog") {
            showingDialog.toggle()
        }
        .padding()
        .sheet(isPresented: $showingDialog, content: {
            GiphyPicker()
                .ignoresSafeArea()
        })
        
    }
}
```
Take a look at this line:
`giphy.swiftUIEnabled = true`
