### ISSUE TITLE
Gifs are covered with a white background when the search keyboard is opened.

### ISSUE THREAD

**Issue by behzod-rajabov** [Giphy/giphy-ios-sdk#217]
## 🐛 Gifs are covered with a white background when the search keyboard is opened.

I am using the SDK with swiftUI. When the search textField is clicked to perform a search, the bottom of the searchTextField is completely covered with a white background. This is related to the keyboard output, because in the Simulator everything works correctly when searching with the keyboard closed via CMD+K.

**Comment by cgmaier** [comment]
hey @behzod-rajabov would it be possible to share a screen shot for what you're experiencing?

**Comment by behzod-rajabov** [comment]
@cgmaier Please refer to the following screenshot and gif:
![Simulator Screen Recording - iPhone 14 Pro - 2023-02-09 at 03 32 37](https://user
![Simulator Screen Shot - iPhone 14 Pro - 2023-02-09 at 03 32 58](https://user-images.githubusercontent.com/46242503/217666417-dc4dc833-8e2e-49a0-8920-916fbae3e271.png)
-images.githubusercontent.com/46242503/217666362-8b0f1231-77ec-4412-8a81-7a0ad0e5f707.gif)

**Comment by cgmaier** [comment]
thanks @behzod-rajabov 
we'll look into this soon. in the meantime, is it possible some of the information in this thread may be helpful to you? 
https://github.com/Giphy/giphy-ios-sdk/issues/44

**Comment by behzod-rajabov** [comment]
Ok @cgmaier I tried the solutions in this thread. They did not benefit.

**Comment by cgmaier** [comment]
hey @behzod-rajabov, it'd help if you can fill out some details about your environment, per the template we kindly ask developers to populate when opening up 'bug reports'

## Your Environment



- Giphy iOS SDK version: 
- Dependency Manager:
- Xcode Version: 
- Swift Version:
- Device info (Simulator/Device? iOS version? Debug/Release?):

we have still been unable to reproduce this on simulator or device.  @ALexanderLonsky demonstrated proper behavior in this [comment](https://github.com/Giphy/giphy-ios-sdk/issues/164#issuecomment-1423067389). can you notice any differences in your implementation?

**Comment by ALexanderLonsky** [comment]
Please refer to the new [SwiftUI example app](https://github.com/Giphy/giphy-ios-sdk/tree/main/SwiftUI-Example)
