### ISSUE TITLE
Can we specify a max gif size?

### ISSUE THREAD

**Issue by AdamBCo** [Giphy/giphy-ios-sdk#218]
## Describe your question in detail.
Is it possible to specify a max gif size for the GiphyViewController? 

For example, I don't want gifs over 1M to be selectable.

**Comment by cgmaier** [comment]
hey @AdamBCo unfortunately this is not possible. however we do provide a `downsized` rendition for every GIF. This is guaranteed to be under 2MB. 

access the downsized rendition URL for a `GPHMedia` like so 
```
let downsizedURL = media.images?.downsized

```
hope this helps!
