### ISSUE TITLE
Cannot build SDK using Xcode 14.3 beta

### ISSUE THREAD

**Issue by lukeredpath** [Giphy/giphy-ios-sdk#221]
## 🐛 Bug Report

A new Xcode beta is out and we cannot currently use it to compile our app because of our dependency on GiphyUISDK.

There are two errors:
```
Failed to build module 'GiphyUISDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)', while this compiler is 'Apple Swift version 5.8 (swiftlang-5.8.0.117.11 clang-1403.0.22.8.60)'). Please select a toolchain which matches the SDK.
```

I don't remember seeing this error with previous betas, I thought binary frameworks were supposed to be forwards compatible.

Also lots of errors about the main actor:

```
Showing Recent Messages
/Users/luke/Library/Developer/Xcode/DerivedData/[redacted]-antubctorcznljcwxglwmvdeclef/Build/Products/Development-iphonesimulator/GiphyUISDK.framework/Modules/GiphyUISDK.swiftmodule/x86_64-apple-ios-simulator.private.swiftinterface:852:17: 'MainActor' is only available in iOS 13.0 or newer
```

## To Reproduce

Open a project that depends on `GiphyUISDK` in Xcode 14.3 beta and try to build.

## Expected behavior

I'd hoped it would build.

## Actual Behavior

It does not build.

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- Giphy iOS SDK version: 2.2.2
- Dependency Manager: SPM
- Xcode Version: 14.3b
- Swift Version: 5.8
- Device info (Simulator/Device? iOS version? Debug/Release?): Debug/Simulator

**Comment by lukeredpath** [comment]
Has the framework been compiled with the `BUILD_LIBRARY_FOR_DISTRIBUTION` setting enabled? AFAIU this is what's required to support forwards compatibility.

**Comment by cgmaier** [comment]
hey @lukeredpath thanks for flagging this. we'll take a look

**Comment by lukeredpath** [comment]
@cgmaier thank you, I appreciate you getting that branch up. It should at least unblock me from taking the Xcode beta for a proper spin.

**Comment by cgmaier** [comment]
@lukeredpath ! sweet, let me know if you have any issues.

**Comment by lukeredpath** [comment]
@cgmaier sorry I forgot to check back in, but the re-built binary on that branch worked for me.

**Comment by cgmaier** [comment]
hey @xmollv thanks for the heads up!

the plan was to make an official release as soon as Xcode 14.3 is released - was thinking there is chance that the final release includes changes that could effect the compiling of the SDK, and there's some risk in the assumption that a xcframework compiled with the beta ot RC won't be compatible with or optimal for the official release. but that's probably negligible. 

will download the RC now and keep you posted

**Comment by xmollv** [comment]
> hey @xmollv thanks for the heads up!
> 
> the plan was to make an official release as soon as Xcode 14.3 is released - was thinking there is chance that the final release includes changes that could effect the compiling of the SDK, and there's some risk in the assumption that a xcframework compiled with the beta ot RC won't be compatible with or optimal for the official release. but that's probably negligible.
> 
> will download the RC now and keep you posted

Awesome, ty! Loos like [Lottie](https://github.com/airbnb/lottie-ios/issues/1963) has a similar issue and they also seem to wait for the final Xcode 14.3 version to take action, seems reasonable to me!

**Comment by cgmaier** [comment]
went forward and made an official release using Xcode 14.3 RC 2 https://github.com/Giphy/giphy-ios-sdk/releases/tag/v2.2.3

**Comment by xmollv** [comment]
> went forward and made an official release using Xcode 14.3 RC 2 https://github.com/Giphy/giphy-ios-sdk/releases/tag/v2.2.3

Hey! I'm not sure if it's really needed in the end. I did try on Monday to build our app again with Xcode 14.3 RC2 on Xcode Cloud and the build that previously failed now passed. I haven't tried yet on my local machine (waiting for next week's final Xcode release). With that I mean that we were still using the `2.2.2` release of Giphy and the build passed without issues.

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/8229382/228779391-158323a2-3a2e-47d8-ae86-d340e204226c.png">

**Comment by cgmaier** [comment]
haha dang!! thanks for sharing that. I just confirmed that `2.2.2` can indeed successfully run in Xcode RC2.

it's reassuring to see that Apple has not broken their promise of 'module stability'. I wonder if this original issue was an unintended bug, or if Apple intended to accept the reality of xcframework incompatibility (presumably as a tradeoff for some other end) until developers complained, especially since there are some big name vendors of closed source projects.

next time I'll be sure to do a deeper dive into the Xcode release notes and ensure I don't miss anything!

as I was under the impression it was necessary to increase min dev target to iOS 13 in order to support Xcode 14.3, I will do a new release to decrease it back down to 10. unfortunately I'm unable to make a new release for a few weeks,
