### ISSUE TITLE
SDK build error using Xcode 14.3 beta 

### ISSUE THREAD

**Issue by madazaharia** [Giphy/giphy-ios-sdk#223]
I can't run the SDK on Xcode 14.3 beta 3. I need help !

Failed to build module 'GiphyUISDK"; this SDK is not supported by the compiler (the SDK is built with 'Apple
X
Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)', while this compiler is 'Apple Swift version 5.8 (swiftlang-5.8.0.124.1 clang-1403.0.22.11.100)'). Please select a toolchain which matches the SDK

**Comment by cgmaier** [comment]
hey @madazaharia there's already an issue for this here, with a solution. I'm going to close this one
https://github.com/Giphy/giphy-ios-sdk/issues/221
