### ISSUE TITLE
Emojis that require skin tone selection are not tappable in landscape

### ISSUE THREAD

**Issue by xmollv** [Giphy/giphy-ios-sdk#233]
## 🐛 Bug Report

Emojis that require the user to select a skin tone (or a variation of the emoji) are not selectable when the device is in landscape. I'm attaching a video of me demonstrating the issue using the provided sample project on this repo (the Swift one).

## To Reproduce

1. Launch the sample project (Swift one) adding your Giphy API key.
2. Tap on the Giphy icon
3. On the modal, select the smiley face (emojis) tab, that'd be the 4th
4. Verify that you can tap on the 👍🏼 emoji in portrait
5. Rotate to landscape
6. Verify that none of the emojis that ask you to pick a color work now

## Expected behavior

The same popup to pick a skin tone should appear so the user can select it.

## Actual Behavior

The popup to select the skin tone doesn't appear if the device is in landscape.

## Your Environment

- Giphy iOS SDK version: 2.2.6
- Dependency Manager: Cocoapods
- Xcode Version: 14.3.1
- Swift Version: 5.8.1
- Device info: Happens in simulator and device (Sim iPhone 11, device iPhone 13 Pro)

## Reproducible Demo

https://github.com/Giphy/giphy-ios-sdk/assets/8229382/ad78bcb7-82dd-499b-aac7-d94fb2354098

**Comment by xmollv** [comment]
@cgmaier just pinging you because we've started getting feedback from our users. Is this something that we can solve from our side or does it need to be fixed at the SDK level? 🙏🏼

**Comment by cgmaier** [comment]
hey @xmollv sorry for the late reply. thanks for sharing this! we were unable to support landscape for the emoji skin tone selection feature. 

we'd love to hear more from you about your experience using GIPHY emoji and any user feedback you can share. could you send any insights to integrations@giphy.com ?

**Comment by xmollv** [comment]
> hey @xmollv sorry for the late reply. thanks for sharing this! we were unable to support landscape for the emoji skin tone selection feature.
> 
> we'd love to hear more from you about your experience using GIPHY emoji and any user feedback you can share. could you send any insights to [integrations@giphy.com](mailto:integrations@giphy.com) ?

I've passed it along to our product team and they'll get in touch on the provided email. Thanks!

**Comment by cgmaier** [comment]
@xmollv that's so awesome, really appreciate it! super helpful to us as we haven't been aware of any apps using the emoji feature. thanks for using the library!
