### ISSUE TITLE
Swift Package Manager can't find Package.swift

### ISSUE THREAD

**Issue by Mxs2019** [Giphy/giphy-ios-sdk#234]
When I try to use this library with Swift Package Manager I get an error where SPM says it can't find the Package.swift file. It says ""giphy-ios-sdk could not be resolved". How can I fix this?

**Comment by hyperlink** [comment]
I was able to get it to work by pinning it to the latest `2.2.6`

**Comment by cgmaier** [comment]
hi @Mxs2019 what were you putting for the Dependency Rule fields when adding the package to your project?

**Comment by Narendrapandey** [comment]
hi @hyperlink  anything you have added to get this SPM, till now I am getting same error

**Comment by ALexanderLonsky** [comment]
@Narendrapandey 
Can you please provide more details? What specifically isn't working for you?

You can refer to this screenshot:
<img width="453" alt="Screenshot 2024-10-18 at 17 20 38" src="https://github.com/user-attachments/assets/92aa2099-0bfb-4fdd-9091-0549bc410be2">

**Comment by eladgel** [comment]
<img width="1006" alt="Screenshot 2024-12-13 at 4 37 23 PM" src="https://github.com/user-attachments/assets/24e6221d-8dd9-4868-9337-a2dae3490927" />
I get this as well, I tried pinning, unpinning and nothing works
