### ISSUE TITLE
EmojiDrawerController

### ISSUE THREAD

**Issue by alirast** [Giphy/giphy-ios-sdk#238]
Hello! I got an UI issue in my project and I have not found any code in docs related to my problem. Using GiphyGridController and having selected some emoji, we get different variations of this emoji (this feature is started from version 2.2.0, https://github.com/Giphy/giphy-ios-sdk/pull/211). Is it possible to disable this feature or to edit the interface of EmojiDrawerController? Thank you in advance.

**Comment by cgmaier** [comment]
thanks for the feedback, I'll pass this along. we should be able to add a flag to disable emoji variations. any reason in particular you'd like to do this ?

**Comment by alirast** [comment]
Thank you so much for the answer. I don't have really strong reason to disable emoji variations. Sure,  I would like to keep it, but just after modifying GiphyGridController to a smaller size I have an issue  - the view of emoji variations (EmojiDrawerController) overlaps the big part of GiphyGridController and it's not comfortable for the user to choose any variant of emoji.

**Comment by cgmaier** [comment]
hey @alirast I'll go forward with adding the ability to disable, but can you please share a screenshot of the UI issue you experienced? maybe we can fix it in a future version.

**Comment by alirast** [comment]
@cgmaier  Hello, sorry for late answer. Thank you for improving that feature for using emoji variations! Now everything works so properly. Thank you!
