### ISSUE TITLE
No visible @interface for 'GiphyGridController' declares the selector 'setAPIKey:verificationMode:'

### ISSUE THREAD

**Issue by junxiangocode** [Giphy/giphy-ios-sdk#240]
I am using Objective C to use this library.

GiphyGridController *vc = [[GiphyGridController alloc] init];
    [vc setAPIKey:GPH_APIKey verificationMode:false]; -->>> this line show error

I Wonder is it whether the library version issue.

**Comment by cgmaier** [comment]
hey @junxiangocode please try
```

    [Giphy configureWithApiKey:@""
              verificationMode:NO
                      metadata:[NSMutableDictionary dictionary]];

```
