### ISSUE TITLE
GiphyCore.shared.gifByID always fails with a 400 for 'text' gifs

### ISSUE THREAD

**Issue by xmollv** [Giphy/giphy-ios-sdk#242]
## 🐛 Bug Report

`GiphyCore.shared.gifByID` always fails if the ID you're using is one retrieved when searching for some text, and tapping the 'text' feature where gifs are created based on what you've typed. Every other type (gifs, stickers, already existing texts, etc) work fine, but not for this case.

I always receive a 
```
▿ Optional<Error>
  ▿ some : GPHHTTPError
    ▿ description : Optional<String>
      - some : "Validation error"
    - statusCode : 400
```

<img width="1057" alt="image" src="https://github.com/Giphy/giphy-ios-sdk/assets/8229382/9b7bb013-010d-48da-8bf0-34a4baff981d">

## To Reproduce

1. Show the `GiphyViewController`
2. Search for 'test'
3. Tap on the colored bubble that contains 'test', right below the search bar
4. Pick the first 'test' text gif
5. Save the `ID`
6. Try to retrieve the media using `GiphyCore.shared.gifByID` and the `ID` you've just saved

## Expected behavior

The media is returned as any other media.

## Actual Behavior

Only on this case the SDK fails to return the gif media.

## Your Environment

- Giphy iOS SDK version: 2.2.7
- Dependency Manager: Swift Package Manager
- Xcode Version: 15.0.1
- Swift Version: 5.9
- Device info (Simulator/Device? iOS version? Debug/Release?): Happens on both device and simulator. iOS 17.

## Demo on how to pick a 'text' gif

https://github.com/Giphy/giphy-ios-sdk/assets/8229382/51e2b546-efd5-4646-b7b3-fcf9e6584b00

**Comment by xmollv** [comment]
@cgmaier Do you know if this is a known limitation of the SDK or it should work? I'd like to know ASAP, because a new app we're building, we're storing IDs (as suggested on the documentation) to be able to send them over the network and retrieve them later on different platforms (to be able to get the appropriate rendition on each platform). If this is a known issue for this kinds of GIFs, we'll have to add more info to our API to be able to also pass a URL instead of just the ID. 

Thanks! 🙏🏼

**Comment by cgmaier** [comment]
hey @xmollv 

sorry for the late reply. please see this documentation 

https://github.com/Giphy/giphy-ios-sdk/blob/main/animate.md#new-gphmedia-property-isdynamic

we'll consider adding this section to the main documentation file to improve visibility 

thanks for using this future btw! very exciting to see developers exploring dynamic text

**Comment by xmollv** [comment]
@cgmaier Thanks for the reply! Understood, we'll change the way we save references to GIPHY elements. 

I don't know what the technical limitation for this is, but if it's doable, please consider supporting the ID for this cases since working with the IDs allows you to get the desired asset on each platform (bigger on desktop, smaller on mobile for example!) instead of having a hardcoded reference to a URL (or needing to save a ton of different URLs when the user selects a gif!).

Feel free to close the issue if it won't be used to work on the ID suggestion! 🙌🏼

**Comment by xmollv** [comment]
> hey @xmollv,
> 
> this is great feedback, thanks!
> 
> unfortunately i don't think we will be able to support static ids for assets like dynamic text, which are rendered on the fly
> 
> just out of curiosity, do you notice prohibitive load times on mobile if you solely were to rely on the largest (`original`) rendition?

I couldn't tell ye since we're still in the building phase, we haven't gotten around to profiling for slow networks yet. I'd assume it won't be a big deal, we ended up going with the route of storing the ID and the original URL. We'll default to the ID for all usage except for the ones where the ID is invalid (aka these dynamic ones) which means that we should be able to get whatever URL we need at any given time for the majority of the gifs!
