### ISSUE TITLE
Apple Privacy Manifest Requirement

### ISSUE THREAD

**Issue by mikemike396** [Giphy/giphy-ios-sdk#247]
Starting May 1st, 2024 Apple will require developers to include approved reasons for the listed APIs used by your app’s code to upload a new or updated app to App Store Connect.

Running this [shell script](https://github.com/Wooder/ios_17_required_reason_api_scanner) I see Giphy marked as using `NSUserDefaults`

```
Used symbols in binary ./GiphyUISDK.framework/GiphyUISDK: NSUserDefaults
```

#### Resources:
https://developer.apple.com/news/?id=3d8a9yyh
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests

Thank you

**Comment by cgmaier** [comment]
hey @mikemike396, thanks for flagging for us. we are working on this and will keep you in the loop!

**Comment by DragonCherry** [comment]
Are there any plans to apply it to version 2.1.x separately as well? 
For some of the legacy systems I run, we are using fixed version of 2.1.x for some reasons.

**Comment by cgmaier** [comment]
Hey @DragonCherry, unfortunately this may not be possible for us. However, you should be able to list the use of `NSUserDefaults` in your app's own privacy manifest file to comply with the App Store requirements. 

The SDK uses user defaults to support the `recently picked` and `recent searches` features built into the templated experience, however we've found an alternative for supporting those features so will be removing our use of the API in the next release. 

Are your reasons for sticking with the `2.1.x` versions compiler version related or is there something we might be able to do to get your running the latest nd greatest?

**Comment by DragonCherry** [comment]
It's not a problem with the framework you provide, thanks anyway 👍

**Comment by a1cooke** [comment]
Hi, We are getting pretty close to May 1 is there a timeline for a release that contains the Privacy Manifest?

**Comment by cgmaier** [comment]
hey @a1cooke / all, 
thanks for your patience! just pushed a new version. let me know if you have any issues

**Comment by a1cooke** [comment]
Thanks so much @cgmaier! Will the updates to Cocoapods propagate shortly also?
