### ISSUE TITLE
SwiftUI Example

### ISSUE THREAD

**Issue by AlexClarkQP** [Giphy/giphy-ios-sdk#44]
Do you have any documentation for SwiftUI integration? Specifically I’d like to show the GiphyViewController in sheet but it’s showing a sheet within a sheet which looks a little awkward.

Here's the code I have so far:

```
import GiphyUISDK
import GiphyCoreSDK
import SwiftUI

struct GiphyPicker: UIViewControllerRepresentable {
    func makeUIViewController(context: UIViewControllerRepresentableContext<GiphyPicker>) -> GiphyViewController {
        GiphyViewController()
    }
    
    func updateUIViewController(_ uiViewController: GiphyViewController, context: UIViewControllerRepresentableContext<GiphyPicker>) {
    }
}
```

and in my view:

```
.sheet(isPresented: showGiphy) {
     GiphyPicker()
}
```

**Comment by cgmaier** [comment]
hey @AlexClarkQP i'm actually not sure ! have not yet explored it 

https://developer.apple.com/tutorials/swiftui/interfacing-with-uikit
you can't find the answer here?

**Comment by AlexClarkQP** [comment]
The interfacing with UIKit is fine. I think it's more an issue with how GiphyViewController presents itself. It appears to present itself in a tray over an existing view (rather than just being the entire view). So if you present it over your entire app it looks fine. However, if you present it in a sheet (the new preferred modal style in iOS 13) it looks odd. I've attached a screenshot. I was wondering if there's a setting to have GiphyViewController just show itself in a full screen view rather than in a tray.  I've tried trayHeightMultiplier but it doesn't fill the screen.

![Original](https://user-images.githubusercontent.com/54222682/70952299-ac4a2400-201a-11ea-82e4-b66f612a0ac8.png)

**Comment by ealeksandrov** [comment]
GiphyViewController is still useless in SwiftUI.
I've used GiphyGridController as a fallback, but it's quite limited in comparison.

For example, SCSDKBitmojiStickerPickerViewController from Snapchat has similar controls (search + stickers), but doesn't hijack whole screen and works well as UIViewControllerRepresentable inside SwiftUI.

Simple GiphyGridController as UIViewControllerRepresentable implementation (no search, just trending GIFs):
```swift
struct GiphySheet: UIViewControllerRepresentable {
    typealias UIViewControllerType = GiphyGridController

    let pickedImageCallback: (String) -> Void

    func makeUIViewController(context: Context) -> GiphyGridController {
        let giphyVC = GiphyGridController()
        giphyVC.delegate = context.coordinator
        giphyVC.content = GPHContent.trending(mediaType: .gif)
        giphyVC.update()
        return giphyVC
    }
    func updateUIViewController(_ uiViewController: GiphyGridController, context: Context) {}

    func makeCoordinator() -> Coordinator {
        Coordinator(self)
    }

    class Coordinator: NSObject, GPHGridDelegate {
        var parent: GiphySheet

        init(_ giphySheet: GiphySheet) {
            self.parent = giphySheet
        }

        func contentDidUpdate(resultCount: Int) {
            //
        }

        func didSelectMedia(media: GPHMedia, cell: UICollectionViewCell) {
            parent.pickedImageCallback(media.url)
        }
    }
}
```

**Comment by schazers** [comment]
+1 on this! Am using SwiftUI, and this would be very helpful 👍

**Comment by schazers** [comment]
Just a note to @ealeksandrov and anyone who finds the info useful: GiphyViewController is not useless in SwiftUI, as you stated above. I just dropped it into my app and am happy using it. I am wrapping it inside a UIVIewControllerRepresentable, presenting it atop a live camera view by using a ZStack. I'm placing the view atop a semi-transparent black background, and providing the top and bottom of the view with some padding. It's working great. It would be nice to have some extra SwiftUI support without having to wrap it, of course, but it's not much work to do it ourselves. It would also be nice, Giphy team, to have SwiftUI-friendly ways to render the returned media. Still a very useful controller to drop in, though. Thanks for providing it.

**Comment by ealeksandrov** [comment]
Thank you for sharing your solution @schazers! This is a viable option for full-screen popover (but I haven't fully tested it).

Unfortunately it won't fit some use cases, like showing GIFs picker below the input field, in place of keyboard:

![comparison](https://user-images.githubusercontent.com/3132438/111033258-56cd1480-8421-11eb-8ea9-1a46a2e817c9.jpg)

As you can see - `SCSDKBitmojiStickerPickerViewController` works fine, because it doesn't expect to handle whole screen  interaction, it just works anywhere you place it. `GiphyGridController` example also works fine, but lacks some features like search.

**Comment by puelocesar** [comment]
IMO, the best way of doing it is using Introspect:

```
.introspectViewController { controller in
                guard presentingGiphy else { return }
                let giphyController = GiphyViewController()
                giphyController.delegate = myViewModel
                controller.present(giphyController, animated: true, completion: nil)
            }
```

**Comment by Patresko** [comment]
Still no better support for swiftui in 2022?

**Comment by kwikysw** [comment]
Beautiful, thank you @Patresko. I find it pretty mind-blowing that there is no "native" way in 2024 (AFAIK?).

**Comment by ALexanderLonsky** [comment]
Please refer to the new [SwiftUI example app](https://github.com/Giphy/giphy-ios-sdk/tree/main/SwiftUI-Example)
