### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by itzaks** [Giphy/giphy-ios-sdk#49]
Hi!

Any plans for making this available as SPM? 

Cheers

**Comment by cgmaier** [comment]
hey @itzaks! it would be great to support SPM at some point, though we currently have no plans to do so. I'll take note of your request with my team and get back to you if anything changes.

**Comment by cgmaier** [comment]
hey @itzaks we looked into this and it turns out swift package manager doesn't support binary frameworks at the moment - only source code. from what I can see there is a lot of demand for this though, so hopefully some day ! 

i'm going to go ahead and close this cc @giorgia

**Comment by itzaks** [comment]
I see, thanks for informing!

**Comment by derekbrown** [comment]
@cgmaier https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages

Please? 🙏

**Comment by arthurschiller** [comment]
Any news here? We would love to fully migrate from CocoaPods soon and GIPHY is one of the last libraries with missing support.

**Comment by schazers** [comment]
+1! This would be very helpful. SPM is wonderful and growing quickly. :)

**Comment by cgmaier** [comment]
we hope to look into this soon - will keep y'all in the loop !

**Comment by schazers** [comment]
👏👏 go giphy team, go 🥳

**Comment by SocialKitLtd** [comment]
Can't wait!

**Comment by andreyoshev** [comment]
+1

**Comment by Sunrizzin** [comment]
+1

**Comment by smocer** [comment]
up

**Comment by osipovka** [comment]
hi, any news here?

**Comment by andreyoshev** [comment]
up

**Comment by cgmaier** [comment]
hey all - thanks for bumping this. we had a chance to make some good progress on this. we plan to support 'officially' in early 2021.

**Comment by cgmaier** [comment]
hi we have SPM working for the latest version: 
https://github.com/Giphy/giphy-ios-sdk/releases

please let us know if you have any issues! 

thanks for your patience
